import "./globals.css";
import Navbar from "@/app/nav/Navbar";
import React from "react";

export const metadata = {
  title: "Asta4Route",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className={"container mx-auto px-5 pt-10"}>{children}</main>
      </body>
    </html>
  );
}
